import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/header"
import Footer from "@/components/Footer/footer"

export const metadata: Metadata = {
  title: "EletroCars",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="pt-br">
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
